### ISSUE TITLE
Performance Issue having [ 404 vars -- 211 cstrs ]

### ISSUE THREAD

**Issue by Andreeew91** [chocoteam/choco-solver#539] opened 2017-06-23 07:39 UTC
Hi there!
Iterating thru all the solution, choco gets stuck at arround solution 330.000 - is that a limitation of choco solver or did I do something wrong with declaring the constraint? Here's my code:

                Model model;
		int[] solvingResult;
		IntVar[] intVariables;
		int[] cssCoeffs;
		IntVar grossMargin;
		int grossMargingResult = 0;

		model = new Model("KEO");
		solvingResult = new int[powerPlantDataList.size()];
		intVariables = new IntVar[powerPlantDataList.size()];
		cssCoeffs = new int[powerPlantDataList.size()];

		for (int i = 0; i < solvingResult.length; i++) {
			intVariables[i] = model.intVar("x" + i, 0, (int) powerPlantDataList
					.get(i).getPMax());
		}

		grossMargin = model.intVar("db", -1000000, 1000000);

		int j = 0;
		for (PowerPlantData ppd : powerPlantDataList) {
			cssCoeffs[j] = (int) ppd.getCssHigh();
			System.out.println(cssCoeffs[j]);
			j++;
		}

		model.scalar(intVariables, cssCoeffs, "=", grossMargin).post();

		for (int i = 0; i < powerPlantDataList.size() - 2; i += 2) {
			model.arithm(intVariables[i], "=", intVariables[i + 1]).post();
		}

		model.setObjective(Model.MAXIMIZE, grossMargin);
		System.out.printf("%s\n", model.toString());
		Solver solver = model.getSolver();

		int counter = 0;
		while (solver.solve()) {
			System.out.println(counter + ". Durchgang von solve()");
			counter++;
			for (int i = 0; i < intVariables.length; i++) {
				solvingResult[i] = intVariables[i].getValue();
				grossMargingResult = grossMargin.getValue();
			}
		}
		System.out.println("Deckungsbeitrag gesamt: " + grossMargingResult);

		int a = 0;
		for (PowerPlantData ppd : powerPlantDataList) {
			ppd.setScheduleHigh(solvingResult[a]);
			a++;
		}

**Comment by cprudhom** [comment] 2017-06-23 08:19
That's not clear to me, what do mean by "solution 330.000": is it the value of the objective or the number of solutions ?
If it is the objective value, maybe that's the optimum and the solver is trying to prove it and can take some time.

**Comment by Andreeew91** [comment] 2017-06-23 08:20
With: 

```
for (int i = 0; i < powerPlantDataList.size() - 2; i += 2) {
		model.arithm(intVariables[i], "=", intVariables[i + 1]).post();
	}
```

I want to tell choco only consider solutions where a pair of values have the same values. So far this constraint is bound to the position. My intention ist to tell choco only to consider solutions where 4 following values are the same. But I haven't figured out so far how to build that constraint

**Comment by Andreeew91** [comment] 2017-06-23 08:20
I'm sorry - that's the number of the solution.

**Comment by Andreeew91** [comment] 2017-06-23 08:22
At the beginning it's working pretty fast. Until maybe arround solution 250.000. At that point every further solution takes more time. At arround 330.000 it's running infinite

**Comment by cprudhom** [comment] 2017-06-23 08:32
Can you give the coefficients as Java int array, please ?

**Comment by Andreeew91** [comment] 2017-06-23 08:34
int[] cssCoeffs = new int[] { 3, -3, -10, -16, -1, -3, -9, -17, -8,
				-11, -8, -8, -15, -19, -16, -9, -29, -26, -12, -6, -27, -15,
				-9, -2, -7, -3, -1, 0, 0, 3, 0, 2, 0, 0, -4, -8, 1, -2, -5,
				-18, 2, -3, -15, -24, -10, -12, -12, -12, -17, -19, -24, -28,
				-21, -21, -33, -43, -30, -31, -34, -34, -34, -33, -30, -25,
				-35, -30, -21, -21, -28, -19, -13, -3, -23, -11, 0, 13, -14,
				-5, -3, 0, -3, -1, -2, -3, -1, -3, -3, -4, 0, 0, -1, -4, 0, -2,
				-19, -31, -1, -5, -15, -21, -11, -12, -18, -20, -11, -15, -15,
				-13, -10, -10, -12, -11, -18, -15, -8, -5, -17, -12, -8, -5,
				-13, -9, -9, -13, -13, -9, -8, -7, -9, -9, -5, -6, -7, -4, -6,
				-10, -3, -6, -9, -11, -8, -6, -7, -11, -5, -7, -11, -15, -4,
				-8, -11, -13, -12, -11, -9, -8, -17, -13, -7, -3, -17, -9, -4,
				0, -14, -6, 1, 7, -10, -1, 4, 10, -2, 2, 6, 11, 2, 3, 6, 8, 6,
				5, 6, 6, 11, 9, 5, 1, 12, 8, 2, -2, 4, 0, -4, -7, 0, -2, -7,
				-8, -3, -5, -6, -6, -7, -8, -8, -4, -7, -7, -7, -7, -4, -5,
				-10, -11, 0, -5, -9, -20, -5, -9, -9, -11, -5, -8, -10, -12,
				-1, -3, -8, -13, -3, -6, -11, -14, -5, -4, -6, -12, -5, -9,
				-15, -20, -9, -12, -17, -23, -16, -17, -19, -17, -26, -19, -15,
				-10, -27, -18, -9, -3, -23, -9, 1, 7, -9, 0, 9, 18, 0, 7, 13,
				17, 6, 8, 12, 15, 7, 7, 10, 13, 16, 15, 11, 7, 15, 11, 4, 0, 4,
				1, 0, -1, 0, 0, -1, -2, 0, -2, -2, -2, -5, -4, -4, 0, -8, -5,
				-2, -1, -6, -5, -2, 3, 0, 6, 9, 12, 15, 16, 15, 15, 26, 20, 14,
				9, 25, 19, 13, 5, 21, 15, 6, 1, 15, 10, 8, 1, 8, 3, 1, -1, 8,
				4, 1, -3, 0, 1, 2, 4, -2, 1, 4, 7, -4, 1, 8, 14, -1, 7, 18, 24,
				4, 13, 22, 31, 15, 20, 22, 26, 16, 14, 15, 15, 14, 12, 10, 8,
				17, 14, 7, 3, 11, 8, 2, 0 };

**Comment by cprudhom** [comment] 2017-06-23 08:40
I get only one solution (and I set `(int) powerPlantDataList.get(i).getPMax()` to 440)...

**Comment by cprudhom** [comment] 2017-06-23 08:57
I'm unable to reproduce the issue for now. Could you give me the upper bound of each variable ?

**Comment by Andreeew91** [comment] 2017-06-23 09:04
I've set the upper bound to 440 now, but I'm still getting thousands of solutions. The following code is the one I last ran and should work as it is on you're system. The iterating get stuck now at arround the 55.000th solution.


```
import org.chocosolver.solver.Model;
import org.chocosolver.solver.Solver;
import org.chocosolver.solver.variables.IntVar;

public class MainTest {

	public static void main(String[] args) {

		Model model;
		int[] solvingResult;
		IntVar[] intVariables;
		int[] cssCoeffs = new int[] { 3, -3, -10, -16, -1, -3, -9, -17, -8,
				-11, -8, -8, -15, -19, -16, -9, -29, -26, -12, -6, -27, -15,
				-9, -2, -7, -3, -1, 0, 0, 3, 0, 2, 0, 0, -4, -8, 1, -2, -5,
				-18, 2, -3, -15, -24, -10, -12, -12, -12, -17, -19, -24, -28,
				-21, -21, -33, -43, -30, -31, -34, -34, -34, -33, -30, -25,
				-35, -30, -21, -21, -28, -19, -13, -3, -23, -11, 0, 13, -14,
				-5, -3, 0, -3, -1, -2, -3, -1, -3, -3, -4, 0, 0, -1, -4, 0, -2,
				-19, -31, -1, -5, -15, -21, -11, -12, -18, -20, -11, -15, -15,
				-13, -10, -10, -12, -11, -18, -15, -8, -5, -17, -12, -8, -5,
				-13, -9, -9, -13, -13, -9, -8, -7, -9, -9, -5, -6, -7, -4, -6,
				-10, -3, -6, -9, -11, -8, -6, -7, -11, -5, -7, -11, -15, -4,
				-8, -11, -13, -12, -11, -9, -8, -17, -13, -7, -3, -17, -9, -4,
				0, -14, -6, 1, 7, -10, -1, 4, 10, -2, 2, 6, 11, 2, 3, 6, 8, 6,
				5, 6, 6, 11, 9, 5, 1, 12, 8, 2, -2, 4, 0, -4, -7, 0, -2, -7,
				-8, -3, -5, -6, -6, -7, -8, -8, -4, -7, -7, -7, -7, -4, -5,
				-10, -11, 0, -5, -9, -20, -5, -9, -9, -11, -5, -8, -10, -12,
				-1, -3, -8, -13, -3, -6, -11, -14, -5, -4, -6, -12, -5, -9,
				-15, -20, -9, -12, -17, -23, -16, -17, -19, -17, -26, -19, -15,
				-10, -27, -18, -9, -3, -23, -9, 1, 7, -9, 0, 9, 18, 0, 7, 13,
				17, 6, 8, 12, 15, 7, 7, 10, 13, 16, 15, 11, 7, 15, 11, 4, 0, 4,
				1, 0, -1, 0, 0, -1, -2, 0, -2, -2, -2, -5, -4, -4, 0, -8, -5,
				-2, -1, -6, -5, -2, 3, 0, 6, 9, 12, 15, 16, 15, 15, 26, 20, 14,
				9, 25, 19, 13, 5, 21, 15, 6, 1, 15, 10, 8, 1, 8, 3, 1, -1, 8,
				4, 1, -3, 0, 1, 2, 4, -2, 1, 4, 7, -4, 1, 8, 14, -1, 7, 18, 24,
				4, 13, 22, 31, 15, 20, 22, 26, 16, 14, 15, 15, 14, 12, 10, 8,
				17, 14, 7, 3, 11, 8, 2, 0 };
		IntVar grossMargin;
		int grossMargingResult = 0;

		model = new Model("KEO");
		solvingResult = new int[384];
		intVariables = new IntVar[384];

		for (int i = 0; i < solvingResult.length; i++) {
			intVariables[i] = model.intVar("x" + i, 0, 440);
		}

		grossMargin = model.intVar("db", -1000000, 1000000);

		model.scalar(intVariables, cssCoeffs, "=", grossMargin).post();

		for (int i = 0; i < 384 - 2; i += 2) {
			model.arithm(intVariables[i], "=", intVariables[i + 1]).post();
		}

		model.setObjective(Model.MAXIMIZE, grossMargin);
		System.out.printf("%s\n", model.toString());
		Solver solver = model.getSolver();

		int counter = 0;
		while (solver.solve()) {
			System.out.println(counter + ". Durchgang von solve()");
			counter++;
			for (int i = 0; i < intVariables.length; i++) {
				solvingResult[i] = intVariables[i].getValue();
				grossMargingResult = grossMargin.getValue();
			}
		}
		System.out.println("Deckungsbeitrag gesamt: " + grossMargingResult);

		for (int i = 0; i < 384; i++) {
			System.out.println(solvingResult[i]);
		}
	}
}
```

**Comment by Andreeew91** [comment] 2017-06-23 09:08
To be specific it gets stuck at 55.289 th solution.

55284. Durchgang von solve()
55285. Durchgang von solve()
55286. Durchgang von solve()
55287. Durchgang von solve()
55288. Durchgang von solve()
55289. Durchgang von solve()

After that point the code is not running further. I think it's stuck somewhere inside

**Comment by Andreeew91** [comment] 2017-06-23 09:52
that's the last one:

```
- Solution #55290 found. Model[KEO], 55290 Solutions, MAXIMIZE db = -438240, Resolution time 255.219s, 233446 Nodes (914.7 n/s), 355926 Backtracks, 122715 Fails, 0 Restarts 
	x0 = 440 x1 = 440 x2 = 440 x3 = 440 x4 = 440 x5 = 440 x6 = 0 x7 = 0 x8 = 0 x9 = 0 x10 = 440 x11 = 440 x12 = 440 x13 = 440 x14 = 440 x15 = 440 x16 = 440 x17 = 440 x18 = 0 x19 = 0 x20 = 440 x21 = 440 x22 = 440 x23 = 440 x24 = 0 x25 = 0 x26 = 0 x27 = 0 x28 = 440 x29 = 440 x30 = 440 x31 = 440 x32 = 440 x33 = 440 x34 = 0 x35 = 0 x36 = 440 x37 = 440 x38 = 440 x39 = 440 x40 = 0 x41 = 0 x42 = 440 x43 = 440 x44 = 440 x45 = 440 x46 = 440 x47 = 440 x48 = 440 x49 = 440 x50 = 440 x51 = 440 x52 = 0 x53 = 0 x54 = 440 x55 = 440 x56 = 440 x57 = 440 x58 = 440 x59 = 440 x60 = 440 x61 = 440 x62 = 0 x63 = 0 x64 = 440 x65 = 440 x66 = 0 x67 = 0 x68 = 440 x69 = 440 x70 = 440 x71 = 440 x72 = 440 x73 = 440 x74 = 440 x75 = 440 x76 = 440 x77 = 440 x78 = 440 x79 = 440 x80 = 440 x81 = 440 x82 = 440 x83 = 440 x84 = 440 x85 = 440 x86 = 0 x87 = 0 x88 = 440 x89 = 440 x90 = 440 x91 = 440 x92 = 440 x93 = 440 x94 = 0 x95 = 0 x96 = 440 x97 = 440 x98 = 440 x99 = 440 x100 = 440 x101 = 440 x102 = 440 x103 = 440 x104 = 440 x105 = 440 x106 = 440 x107 = 440 x108 = 440 x109 = 440 x110 = 440 x111 = 440 x112 = 440 x113 = 440 x114 = 440 x115 = 440 x116 = 440 x117 = 440 x118 = 440 x119 = 440 x120 = 440 x121 = 440 x122 = 440 x123 = 440 x124 = 440 x125 = 440 x126 = 440 x127 = 440 x128 = 0 x129 = 0 x130 = 440 x131 = 440 x132 = 440 x133 = 440 x134 = 440 x135 = 440 x136 = 440 x137 = 440 x138 = 440 x139 = 440 x140 = 0 x141 = 0 x142 = 440 x143 = 440 x144 = 440 x145 = 440 x146 = 440 x147 = 440 x148 = 0 x149 = 0 x150 = 440 x151 = 440 x152 = 0 x153 = 0 x154 = 440 x155 = 440 x156 = 440 x157 = 440 x158 = 440 x159 = 440 x160 = 440 x161 = 440 x162 = 0 x163 = 0 x164 = 440 x165 = 440 x166 = 440 x167 = 440 x168 = 440 x169 = 440 x170 = 440 x171 = 440 x172 = 440 x173 = 440 x174 = 440 x175 = 440 x176 = 440 x177 = 440 x178 = 440 x179 = 440 x180 = 440 x181 = 440 x182 = 440 x183 = 440 x184 = 440 x185 = 440 x186 = 440 x187 = 440 x188 = 440 x189 = 440 x190 = 440 x191 = 440 x192 = 440 x193 = 440 x194 = 440 x195 = 440 x196 = 440 x197 = 440 x198 = 0 x199 = 0 x200 = 440 x201 = 440 x202 = 440 x203 = 440 x204 = 440 x205 = 440 x206 = 0 x207 = 0 x208 = 0 x209 = 0 x210 = 440 x211 = 440 x212 = 440 x213 = 440 x214 = 440 x215 = 440 x216 = 440 x217 = 440 x218 = 440 x219 = 440 x220 = 0 x221 = 0 x222 = 440 x223 = 440 x224 = 440 x225 = 440 x226 = 440 x227 = 440 x228 = 440 x229 = 440 x230 = 440 x231 = 440 x232 = 440 x233 = 440 x234 = 440 x235 = 440 x236 = 440 x237 = 440 x238 = 440 x239 = 440 x240 = 440 x241 = 440 x242 = 0 x243 = 0 x244 = 440 x245 = 440 x246 = 440 x247 = 440 x248 = 440 x249 = 440 x250 = 440 x251 = 440 x252 = 440 x253 = 440 x254 = 440 x255 = 440 x256 = 0 x257 = 0 x258 = 440 x259 = 440 x260 = 440 x261 = 440 x262 = 440 x263 = 440 x264 = 440 x265 = 440 x266 = 440 x267 = 440 x268 = 440 x269 = 440 x270 = 440 x271 = 440 x272 = 440 x273 = 440 x274 = 440 x275 = 440 x276 = 440 x277 = 440 x278 = 440 x279 = 440 x280 = 440 x281 = 440 x282 = 440 x283 = 440 x284 = 440 x285 = 440 x286 = 440 x287 = 440 x288 = 440 x289 = 440 x290 = 440 x291 = 440 x292 = 440 x293 = 440 x294 = 440 x295 = 440 x296 = 440 x297 = 440 x298 = 440 x299 = 440 x300 = 440 x301 = 440 x302 = 440 x303 = 440 x304 = 440 x305 = 440 x306 = 440 x307 = 440 x308 = 440 x309 = 440 x310 = 440 x311 = 440 x312 = 440 x313 = 440 x314 = 440 x315 = 440 x316 = 440 x317 = 440 x318 = 440 x319 = 440 x320 = 440 x321 = 440 x322 = 440 x323 = 440 x324 = 440 x325 = 440 x326 = 440 x327 = 440 x328 = 440 x329 = 440 x330 = 440 x331 = 440 x332 = 440 x333 = 440 x334 = 440 x335 = 440 x336 = 440 x337 = 440 x338 = 440 x339 = 440 x340 = 440 x341 = 440 x342 = 440 x343 = 440 x344 = 440 x345 = 440 x346 = 440 x347 = 440 x348 = 440 x349 = 440 x350 = 440 x351 = 440 x352 = 440 x353 = 440 x354 = 440 x355 = 440 x356 = 440 x357 = 440 x358 = 440 x359 = 440 x360 = 440 x361 = 440 x362 = 440 x363 = 440 x364 = 440 x365 = 440 x366 = 440 x367 = 440 x368 = 440 x369 = 440 x370 = 440 x371 = 440 x372 = 440 x373 = 440 x374 = 440 x375 = 440 x376 = 440 x377 = 440 x378 = 440 x379 = 440 x380 = 440 x381 = 440 x382 = 440 x383 = 440 IV_1 = -82280 IV_2 = -19800 IV_3 = -195800 IV_4 = -79200 IV_5 = -55000 IV_6 = -105600 IV_7 = -54120 IV_8 = -58960 IV_9 = 44000 IV_10 = -15840 IV_11 = -63800 IV_12 = -95920 IV_13 = -19800 IV_14 = 68200 IV_15 = -14520 IV_16 = 123640 IV_17 = 24640 IV_18 = 148280 IV_19 = 13640 db = -438240 .
```

**Comment by cprudhom** [comment] 2017-06-23 10:53
Ok, I'm now able to reproduce it. 
I'll see what I can do, but you should add an accurate strategy like the one I declared on the previous issue.

**Comment by cprudhom** [comment] 2017-06-23 10:57
With a good strategy, I found `db = 481800` in 881 solutions.
It is still running without ending, but at least the last solution is really better.
I'll keep on looking.

**Comment by cprudhom** [comment] 2017-06-26 14:24
Hi,

The search space of your problem is really big and the sum constraint is not able to filter enough to remove big parts of the search space by filtering. So, comes a moment where it is hard to find a better solution (or proving the optimality of the last one found) and the "entire" search space has to be explored.

An option is to find symmetry breaking constraint or more efficient strategy.
For example, it seems that each variable is associated to another with equality constraints, but the search strategy does not know about that.
So branching on only one variable among two should be helpful (even though not enough).
```java
IntVar[] dvar = new IntVar[384/2];
for (int i = 0, j = 0; i < 384 - 1; i += 2, j++) {
            model.arithm(intVariables[i], "=", intVariables[i + 1]).post();
            dvar[j] = intVariables[i];
}
//...
solver.setSearch(Search.intVarSearch(
       new InputOrder<>(model),
       (v)-> (map.get(v) < 0 ? v.getLB():v.getUB()),
       dvar
));
```
(NB: is there a bug in the for-loop ? x383 and x384 are not linked together ?)

I believe that a good analysis of the pair of equal variables may help you designing a better strategy by summing consecutive coefficients and branching on UB on positive ones and then on LB of negative ones. Plus, consider sorting decision variables (in `dvars`) by decreasing aggregated coefficients.

Best regards.

**Comment by Andreeew91** [comment] 2017-07-10 07:16
Hi Charles,
thank you very much for your support. Your solution did help very well with the performance issue. I combinded it with a search limit. The linking with of two variables was a first attempt. My real intention ist to tell choco that at least four values in a row (independent of the position) have to have the same value namly maximum of the value of the variable of the four with the smallest initial upper bound. I started a first attempt with a propagator-implementation of my own. The following first attempt to realise that ist not working as expected. If the optimazitaion results in a jump greater or equal than 5 choco should respect the respective propagation. Hope this is not too confusing :-/

 ```
public class ConsistencyPropagator extends Propagator<IntVar> {

	IntVar[] intVarArr;

	public ConsistencyPropagator(IntVar intVarArr[]) {
		super(intVarArr);
		this.intVarArr = intVarArr;
	}

	@Override
	public void propagate(int evtmask) throws ContradictionException {
		for (int i = 3; i < intVarArr.length - 4; i++) {
			if (Math.abs(intVarArr[i].getValue() - intVarArr[i + 1].getValue()) >= 5.0) {

				intVarArr[i + 2].updateLowerBound(intVarArr[i + 1].getLB(),
						this);
				intVarArr[i + 2].updateUpperBound(intVarArr[i + 1].getUB(),
						this);
				intVarArr[i + 3].updateLowerBound(intVarArr[i + 1].getLB(),
						this);
				intVarArr[i + 3].updateUpperBound(intVarArr[i + 1].getUB(),
						this);
				intVarArr[i + 4].updateLowerBound(intVarArr[i + 1].getLB(),
						this);
				intVarArr[i + 4].updateUpperBound(intVarArr[i + 1].getUB(),
						this);

				intVarArr[i - 1].updateLowerBound(intVarArr[i].getLB(), this);
				intVarArr[i - 1].updateUpperBound(intVarArr[i].getUB(), this);
				intVarArr[i - 2].updateLowerBound(intVarArr[i].getLB(), this);
				intVarArr[i - 2].updateUpperBound(intVarArr[i].getUB(), this);
				intVarArr[i - 3].updateLowerBound(intVarArr[i].getLB(), this);
				intVarArr[i - 3].updateUpperBound(intVarArr[i].getUB(), this);
			}
		}
	}

	@Override
	public ESat isEntailed() {
		int a = 0;
		for (int i = 3; i < intVarArr.length - 4; i++) {
			if (Math.abs(intVarArr[i].getValue() - intVarArr[i + 1].getValue()) >= 5.0) {
				if (intVarArr[i + 2].getValue() == intVarArr[i + 1].getValue()
						&& intVarArr[i + 3].getValue() == intVarArr[i + 1]
								.getValue()
						&& intVarArr[i + 4].getValue() == intVarArr[i + 1]
								.getValue()
						&& intVarArr[i - 1].getValue() == intVarArr[i]
								.getValue()
						&& intVarArr[i - 2].getValue() == intVarArr[i]
								.getValue()
						&& intVarArr[i - 3].getValue() == intVarArr[i]
								.getValue()) {
					a = 0;
				} else {
					a = 1;
					break;
				}

			} else {
				a = 0;
			}
		}

		if (a == 1) {
			return ESat.FALSE;
		} else if (a == 0) {
			return ESat.TRUE;
		} else {
			return ESat.UNDEFINED;
		}
	}
}

```

Best regards

**Comment by cprudhom** [comment] 2017-07-10 14:36
Hi,

I would prefer a mathematical formulation of the constraint semantic  and some solutions, or its formulation with choco native constraints.

Best,

**Comment by Andreeew91** [comment] 2017-07-12 16:12
I think I need "default Constraint allEqual(IntVar... vars)" to achieve my goal. 

```
		for (int i = 0; i < powerPlantDataList.size() - 3; i += 4) {
			model.allEqual(intVariables[i], intVariables[i + 1],
					intVariables[i + 2], intVariables[i + 3]).post();
		}
```

With the constraint above I constraint that four values in a row have to have the same value. With the realization above the constraint is depending on the position of the variable. Would you know an attempt to declare that four values in a row independently of their position have to have the same value?

Best Regards 
Andre

**Comment by cprudhom** [comment] 2017-07-13 07:41
Are there exactly 4 variables to be assigned to the same value ?
Is the value specific (like 0 or 440) or it could be any value ?

It the value is specific, let's say 0, you can use a `globalCardinality(IntVar[] vars, int[] values, IntVar[] occurrences, boolean closed)` constraint:
```java
IntVar nbOcc = model.intVar("occ", 4, powerPlantDataList.size());
model.globalCardinality(intVariables, new int[]{0}, nbOcc, false).post();
```
(read the Javadoc for more details about parameters)

If the value is not specific, you can use as many `count(int value, IntVar[] vars, IntVar limit)` as values:
```java
IntVar[] nbOccs = model.intVarArray("nbOccs", powerPlantDataList.size(), 0, 440);
for(int i = 0; i <= 440; i++){
   model.count(i, intVariables, nbOccs[i]).post();
}
model.maximum(model.intVar(4), nbOccs); 
```

NB: the `allEqual(IntVar...)` API relies on a specific instantiation of  `atMostNValues(IntVar[],IntVar,boolean)` where the second parameter is set to `model.intVar(1)` (i.e., all variables should take at most n different values, where n = 1).

**Comment by Andreeew91** [comment] 2017-07-13 15:59
At least four values in a row have to be assigned to the same value. What I don't want is a series like 0,0,0,0,440,440,440,0,0,0,440,0,0,0. What I want to constrain is a series like 0,0,0,0,440,440,440,440,0,0,0,0,0,0,0. If the value of the variable changes the change has to be consistent for at least the following four variables. The value the variable hast to be assigned to is not specific. I think your solution aims a having a value between 0 and 440 assigned maximal four times. Is that right? Thanks for your help!

**Comment by Andreeew91** [comment] 2017-07-13 16:03
And of course a solution like 0,0,0,0,230,230,230,230,230,230,0,0,0,0,0 is also applicable

**Comment by cprudhom** [comment] 2017-07-17 13:30
With your examples, I have the impression that only two values are authorized: 0 and another one, am I wrong ?

Could we consider limiting the number of 0 first (to not be greater than n - 4) ? and then constrain the other values to be equal ?

**Comment by Andreeew91** [comment] 2017-07-18 08:43
I'm sorry - I chose an unsufficient example. Other values are also authorized like: 0,0,0,0,0,0,230,230,230,230,0,0,0,0,0,0,0,0,240,240,240,240,240,240,240,0,0,0,0,0,0 and so on. I don't  see the point in limiting the number of 0 so far because a solution consisting only of zeros is also possible when all coefficients are negative. Can we use the count-constraint to declare that every value that appears has to appear **at least four times** in a row and **not exactly four times**?

**Comment by cprudhom** [comment] 2017-07-18 09:23
Well, in that case, you can try the following approach:
```java 
IntVar[] nbOccs = model.intVarArray("nbOccs", powerPlantDataList.size(), 0, 440);
for(int i = 0; i <= 440; i++){
   model.count(i, intVariables, nbOccs[i]).post();
   if(i>0){
      model.notmember(nbOccs[i], 1, 3).post();      
   }
}

```

For any value, except 0, it should appear 0 or at least 4 times in a solution.
In other words, any value, except 0, cannot appear 1, 2 or 3 times in a solution.
2 alternatives:
- you can avoid `model.notmember ` by declaring more precisely the domains of `nbOccs`,
- you can also consider posting a `globalCardinality` with accurate domains for values and occurrences, but that should almost achieve the same result.

Hope that helps,
CP

**Comment by Andreeew91** [comment] 2017-07-24 15:15
I think you're last solution represents the best progress we've made so far. Thanks very much for that. However, thers's still a problem. We did a limitation of the number of occurences of some values with success, but the order of the values is not considered so far. In other words: A sequence like 0,0,0,0,230,0,0,230,230,230, ist still possible because the value occur at least four times, but not four times in a row. Do you know how we could solve this issue? Best regards Andre

**Comment by Andreeew91** [comment] 2017-07-25 07:21
A diffrent attempt I had in mind was the following:

```
Constraint c = null;
Constraint d = null;
Constraint e = null;
Constraint f = null;
for (int i = 3; i < powerPlantDataList.size() - 3; i++) {
	c = model.distance(intVariables[i + 1], intVariables[i], ">", 3);
	d = model.allEqual(intVariables[i], intVariables[i + 1],
		intVariables[i + 2], intVariables[i + 3]);
	 e = model.allEqual(intVariables[i], intVariables[i - 1],
		intVariables[i - 2], intVariables[i - 3]);
	f = model.and(d, e);
	model.ifThen(c, f);
}
```

Constraint c is needed to check wether the distance between to values is greater than 3 because in the productive Code the UpperBounds of `intVariables ` differ from one to another and it's okay when there are less than four values in a row diffrent, but the diffrence is smaller than 4. If the case is that the diffrence is greater than 3 at least four values forward (and backward) have to be assigned to the same value. However, the attempt is not working out as expected. I think the problem is, that I've declared the constraint for every element in the sequence. Do you understand what I was trying to implement with this attempt? If so, do you see any chances this attempt is working out with proper adaptations? Or should we stick to our last attempt? 

Best regards, 
Andre

**Comment by cprudhom** [comment] 2017-08-16 08:58
Hi,

Then, you should add a `regular` constraint based on a regular expression or a DFA.

Something like this:

```java
model.regular(intVariables, new FiniteAutomaton("0*[^0]{4,}?0*",0,440)).post();
```
Here a DFA is created based on regex `"0*[^0]{4,}?0*"`. Since `[^0]` is used in the regex, it is strongly recommended to define the vocabulary bounds, here 0 and 440.

This constraint comes in complement of the previous model.

Hope it helps,
CP

**Closed** 2017-12-14 13:28 UTC
Labels: support
